### ISSUE TITLE
byte[] can be null

### ISSUE THREAD

**Issue by yoyosource** [JavaFactoryDev/LightningStorage#19]
Hello JavaFactoryDev,
I found something in FileUtils where you are throwing this:
```Java
throw new IllegalStateException("Can't return null as byte[]");
```
The comment `Can't return null as byte[]` is not needed, as I tried in my Java Project (Java Version 12.0.1). I created a Method that expected a byte array as return value and I could just return null.
```Java
public byte[] getBytes() {
    return null;
}
```
I tried this code and my IDE (Intelij IDEA CE) did not warn me that something is wrong. Could it be that you think that byte is a primitive but an array of a primitive is an Object? You can see this in effect while looking at a `List<>`.
```Java
// This does not work as 'byte' is not an Object.
List<byte> bytes = new ArrayList<>();
// This does work because 'byte[]' is a Object.
List<byte[]> bytes = new ArrayList<>();
```

Edit-0:
What about returning an empty byte array instead of returning null?

Edit-1:
Changed some typos.

**Comment by JavaFactoryDev** [comment]
Hey Yoyosource,

Thank you for using LightningStorage and taking the time to write such a detailed report.
We really appreciate it, things like that keep us going:)

Indeed the exception-messages aren't named that easy to understand.

The goal in the FileUtils-class was to break up the whole code if an IOException occurs, to let the user know something went wrong.
The FileUtils class is especially meant to build an abstraction layer for methods with checked-exceptions & create a unified way handling them.

I already improved the code style so this should be clearer.

Maybe you could give us some feedback, whether the new commit "fits your needs" ^^

Regards,
- Leonhard

**Comment by yoyosource** [comment]
Hey JavaFactoryDev,

I was not writing about the clarity. I just wanted to point out that throwing an Exception and catching it again with an Error output to `System.err` is not the smartest solution I can think of. 
I am pleased that you appreciated my detailed report. I am trying to make it as detailed as I can.
As for using LightningStorage, I am not using it right now but I am planing to do so. 

As I understand how throwing and catching Exceptions in Java work they aren't that fast to deal with. So a simple `if (r == null) {}` is faster and easier to use for the programmer using this Library/API. Also I think it is a hazard to print something into console that the user and programmer does not know of beforehand. Those logging Messages most likely irritate or they irritate me.

As for the new commit. I do not see any change in the Method I stated above in my initial Issue. I like you changes regarding clarification but I wasn't having any problem with that. So in this commit I do not see any improvements on my issue just some clarification in the File itself.

This code is what I mean in FileUtils:
```Java
public byte[] readAllBytes(final File file) {
    try {
        return Files.readAllBytes(file.toPath());
    } catch (final IOException ex) {
        System.err.println("Exception while reading '" + file.getName() + "'");
        System.err.println("In '" + getParentDirPath(file) + "'");
        throw new IllegalStateException("Can't return null as byte[]");
    }
}
```
Also I would propose to check if `file` is null first before using the other methods like `file.getName()` and `getParentDirPath()` because they could throw a `NullPointerException`. Just the method call can cause that.

Regards,
* YoyoSource

**Comment by yoyosource** [comment]
Thanks for the second enhancement.
I just wanted to state that maybe you should make the error messages optional like toggle it with a method call or set it to a specific flag.

```Java
public static setErrorMessages(boolean active) {}
public static toggleErrorMessages() {}
```
Just as an example.
