### ISSUE TITLE
remove() results in ArrayIndexOutOfBoundsException

### ISSUE THREAD

**Issue by test414EFF** [JavaFactoryDev/LightningStorage#21]
**Describe the bug**
Trying to use remove() to delete a hashmap in a JSON file results in this error:
https://hastebin.com/ovasapukam.sql

**To Reproduce**
Use remove() on a hashmap in a json file. I have not tested this with other file types or other datatypes.

**Expected behavior**
I expected this to remove the data from the file. 

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome
 - Version 3.0.0 (Didn't realize that there was a new version, though it doesn't look like it's changed much so it should still be the same. Will test and edit if anything changes upon updating to 3.0.1)

**Comment by JavaFactoryDev** [comment]
Hey 414EFF,

Can you please provide some sample code to reproduce this error.

Regards,
- Leonhard from Mineacademy

**Comment by test414EFF** [comment]
Sure. I'm using this to create the item I'm trying to delete (it's a shop):
`HashMap<String, HashMap> shop = new HashMap<>();
HashMap<String, String> items = new HashMap<>();
HashMap<String, Object> info = new HashMap<>();

items.put(serializer.itemToString(item), price.toString());
info.put("owner", utility.getUUID(p));
shop.put("items", items);
shop.put("info", info);
shops.set(name.toString(), shop);`


And this code to remove it:
`shops.remove(name);`

**Comment by JavaFactoryDev** [comment]
Hi 414EFF,

We fixed this issue with the latest version:)
Thank you for reporting it.

Regards,
- Leonhard
