### ISSUE TITLE
Example Config files

### ISSUE THREAD

**Issue by yoyosource** [JavaFactoryDev/LightningStorage#22]
Hello JavaFactoryDev,
I looked through your code and tried to look at examples for every config format you support. I was thinking about some JSON examples, some YAML examples, some TOML examples and some LightningFile examples. It would help me and some other creators to get some examples and ideas how to use the config files. This would especially be useful for the LightningFile as there is no known documentation I have found.

Regards,
* yoyosource

Edit-0:
Regards section

**Comment by JavaFactoryDev** [comment]
Thanks to Magnum97 we now have examples #30 
We will add them to the wiki over the weekend
