### ISSUE TITLE
Code improvements

### ISSUE THREAD

**Issue by JarFiles** [JavaFactoryDev/LightningStorage#27]
- Custom exception instead of just printing the error
- Don't use raw types for parametized classess
- Use Apache's Lang Validator (Because it has a better ide implementation)
- Code Formatting / Naming is sometimes a bit inconsistent (Throwable e / Throwable ex) 
- Always use the absolute filepath in error messages. Makes debugging a lot simpler

**Comment by JavaFactoryDev** [comment]
Hey Justin, 

Thank you for providing these enhancements. We will consider adding it.

Regards,
- Leonhard
