### ISSUE TITLE
List not stored as expected in Lightning storage file

### ISSUE THREAD

**Issue by Magnum97** [JavaFactoryDev/LightningStorage#29]
**Describe the bug**
LightningStorage file type does not store list correctly

**To Reproduce**
1. Create String array
2. Create Lightning file and store array as list
3. See result:
<details><summary>Method used to create files</summary>

```
private void setupConfig () {
        String string1 = "string";
        String nest1 = "Nested Value";
        String nest2 = "Another nested value";
        String[] list = new String[]{"List item one", "Another item", "The last one, I promise"};
        int ultimateAnswer = 42;
        boolean boo = true;
        Json json = new Json("lightning.json", getDataFolder().toString());
        Yaml yaml = new Yaml("lightning.yaml", getDataFolder().toString());
        Toml toml = new Toml("lightning.toml", getDataFolder().toString());
        LightningFile lightningFile = new LightningFile("lightning.ltn", getDataFolder().toString());
        List <String> header = new ArrayList <String>();

        header.add("This is a header");
        header.add("It supports array list");
        header.add("for multiple line comments.");
        header.add("Only available in YAML");

        json.setDefault("key1", string1);
        json.setDefault("nested.key1", nest1);
        json.setDefault("nested.key2", nest2);
        json.setDefault("next_key", "next_value");
        json.setDefault("the_answer_to_everything", ultimateAnswer);
        json.setDefault("listExample", list);

        yaml.setHeader(header);
        yaml.write();
        yaml.setDefault("key1", string1);
        yaml.setDefault("nested.key1", nest1);
        yaml.setDefault("nested.key2", nest2);
        yaml.setDefault("next_key", "next_value");
        yaml.setDefault("the_answer_to_everything", ultimateAnswer);
        yaml.setDefault("listExample", list);

        toml.setDefault("key1", string1);
        toml.setDefault("nested.key1", nest1);
        toml.setDefault("nested.key2", nest2);
        toml.setDefault("next_key", "next_value");
        toml.setDefault("the_answer_to_everything", ultimateAnswer);
        toml.setDefault("listExample", list);

        lightningFile.setDefault("key1", string1);
        lightningFile.setDefault("nested.key1", nest1);
        lightningFile.setDefault("nested.key2", nest2);
        lightningFile.setDefault("next_key", "next_value");
        lightningFile.setDefault("the_answer_to_everything", ultimateAnswer);
        lightningFile.setDefault("listExample", list);
}
```
</details>

<details><summary>Resulting storage file</summary>

<pre>
key1 = string
nested {
  key1 = Nested Value
  key2 = Another nested value
}
next_key = next_value
the_answer_to_everything = 42
listExample = [Ljava.lang.String;@25288e12
</pre>
</details>

**Expected behavior**
Strings would be stored, not just a reference to java object.
Also tested with Json, Yaml and Toml with perfect results. I realize this is an array, not a list and is similar to #20 but not quite the same as I am using v3.1.0
<details><summary>Expected results achived with Json, Yaml, & Toml:</summary>

<pre>
{
   "key1": "string",
   "listExample": [
      "List item one",
      "Another item",
      "The last one, I promise"
   ],
   "next_key": "next_value",
   "nested": {
      "key1": "Nested Value",
      "key2": "Another nested value"
   },
   "the_answer_to_everything": 42
}

key1: string
nested: 
   key1: Nested Value
   key2: Another nested value
next_key: next_value
the_answer_to_everything: 42
listExample: 
- List item one
- Another item
- The last one, I promise

key1 = "string"
next_key = "next_value"
the_answer_to_everything = 42
listExample = ["List item one", "Another item", "The last one, I promise", ]

[nested]
key1 = "Nested Value"
key2 = "Another nested value"
</details>
</pre>

**Desktop (please complete the following information):**
 - OS: Linux 5.3.0-46-generic x86_64 GNU/Linux
 - Browser Chrome
 - Version: 81.0.4044.138-1

**Smartphone (please complete the following information):**
- OS: Android
- Browser: Chrome

**Additional context**

**Comment by JavaFactoryDev** [comment]
Hey Magnum97,

thank you so much for your detailed issue report & your dedication to help us.

We will have a look soon.

Regards,
- Leonhard

**Comment by JavaFactoryDev** [comment]
Hey we have decided not to support LightningFile anymore, as it was developed by a developer that is not active on this project anymore.

It was deleted in the latest version of LightningStorage.
