### ISSUE TITLE
Maven Repository is out of date

### ISSUE THREAD

**Issue by nsporillo** [JavaFactoryDev/LightningStorage#3]
Cannot use the latest version because it is not present in the Nexus repository. 

I manually browsed the Nexus repository and only up to version 1.9.1 is present.

I can fork the repository and `compile install` it manually, but that isn't ideal especially since there is a Nexus repository available.

Looking forward to incorporating JSON based storage for GlobalWarming, but would like to see the latest artifacts uploaded. Thanks!

**Comment by JavaFactoryDev** [comment]
You're right, the repo is outdated.
This is because LightningStorage has migrated to JitPack.
The description of the GitHub page is wrong. 
Thanks for the hint!

Here are the correct dependencies again:
Can also be found here: https://jitpack.io/#JavaFactoryDev/LightningStorage/2.3.8
```xml

       <repository>
                <id>jitpack.io</id>
               <url>https://jitpack.io</url>
	</repository>

       <dependency>
	    <groupId>com.github.JavaFactoryDev</groupId>
	    <artifactId>LightningStorage</artifactId>
	    <version>2.3.8</version>
	</dependency>
```
