### ISSUE TITLE
The Yaml configs have new lines after each key

### ISSUE THREAD

**Issue by Leonardo-DGS** [JavaFactoryDev/LightningStorage#31]
**Describe the bug**
LightningStorage generates a new line character after each Yaml config key and even a space after a section key, it's annoying.
If it is expected, in the API should be added the mentioned styling options.

**Code**
```java
        Yaml yamlConfig = LightningBuilder
                .fromPath("test.yml", getDataFolder().getPath())
                .setDataType(DataType.SORTED)
                .setConfigSettings(ConfigSettings.PRESERVE_COMMENTS)
                .setReloadSettings(ReloadSettings.MANUALLY)
                .createConfig();


        yamlConfig.addHeader("asdasd", "abbbb");
        yamlConfig.setPathPrefix("taaaa");
        yamlConfig.setDefault("b", "asdsadads");
        yamlConfig.setDefault("a", 32);
        yamlConfig.setDefault("c.a", "tetetetesst");
```

**Config output**
```yaml
taaaa: 

   a: 32

   b: asdsadads

   c: 

      a: tetetetesst


```

**Expected behavior**
I expected that Yaml configs would be generated like in the screenshots in the SpigotMC plugin page.

**Comment by Leonardo-DGS** [comment]
Now, with the version 3.1.5, it's fixed the empty line between each config entry, but still there is the space after the section key.

**Comment by Leonardo-DGS** [comment]
This happens only when the option `ConfigSettings` is set to `PRESERVE_COMMENTS`

**Comment by JavaFactoryDev** [comment]
Yeah, this is known and it only happens with no comments at all.
I can have a look at it.

**Comment by Leonardo-DGS** [comment]
@JavaFactoryDev it happens even if there are comments, and after each comment are inserted several empty lines.

**Comment by JavaFactoryDev** [comment]
Should be fixed with the latest release.

**Comment by JavaFactoryDev** [comment]
Please tell me whether is still occurs or not.

**Comment by Leonardo-DGS** [comment]
@JavaFactoryDev now this bug no longer occurs, but `Yaml#addHeaders` and `Yaml#setHeaders` works only if there is at least one empty line or comment at the beginning of the file.

**Comment by JavaFactoryDev** [comment]
Thanks for reporting it! This is indeed intended as we can't distinguish between both if there are no empty lines.
