### ISSUE TITLE
Console spam on removing entries

### ISSUE THREAD

**Issue by onDee** [JavaFactoryDev/LightningStorage#4]
**Describe the bug**
When you remove something from storage, there is a console spam.

**To Reproduce**
1. Remove entry from storage.

**Expected behavior**
No console output when removing entries from storage.

**Comment by onDee** [comment]
https://github.com/JavaFactoryDev/LightningStorage/blob/63a7086cf8cb5f7dc87fdbb69e730455ad07980f/src/main/java/de/leonhard/storage/util/Utils.java#L116-L117

**Comment by JavaFactoryDev** [comment]
Hi, thank you for using LightningStorage & your help to improve it!
This Bug is now fixed. Thanks. Please update to 2.4
