### ISSUE TITLE
Can't Modify Json File

### ISSUE THREAD

**Issue by OfficialDonut** [JavaFactoryDev/LightningStorage#6]
**Describe the bug**
Json files can't be modified because of an input stream not being closed. I believe this input stream is the problem:
https://github.com/JavaFactoryDev/LightningStorage/blob/63a7086cf8cb5f7dc87fdbb69e730455ad07980f/src/main/java/de/leonhard/storage/Json.java#L36
If the input stream does need to constantly stay open can you add a close() method that we can call when we're done with the json so we can modify the file?

**To Reproduce**
I was specifically testing with deleting the json file which fails since the input stream isnt closed
```
Json json = new Json("test", "C:\\some\\path\\");
Files.delete(json.getFile().toPath());
```
```
Caused by: java.nio.file.FileSystemException: The process cannot access the file because it is being used by another process.
```

**Comment by JavaFactoryDev** [comment]
Hi, this Bug is fixed with 2.4, too.
