### ISSUE TITLE
Shade problem

### ISSUE THREAD

**Issue by theocerdan** [JavaFactoryDev/LightningStorage#7]
**Describe the bug**
java.lang.ClassNotFoundException

**To Reproduce**
My pom.xml : https://pastebin.com/YksCJG6B
My package: https://i.imgur.com/AVoa4K8.png
My code: https://i.imgur.com/HZsbRFi.png
The error: https://i.imgur.com/eB7eUiS.png

**Comment by JavaFactoryDev** [comment]
If the LightningStorage-classes would be shaded, the ClassNotFoundError wouldn't occur in the de.leonhard.storage package.
As I've said, I would need your source to see, what's wrong.

**Comment by theocerdan** [comment]
https://gitlab.com/cerdantheo.contact/hestia-core

**Comment by theocerdan** [comment]
https://gitlab.com/cerdantheo.contact/hestia-core

**Comment by JavaFactoryDev** [comment]
I will take a look.

**Comment by theocerdan** [comment]
do you find something ?

**Comment by JavaFactoryDev** [comment]
No errors found yet, worked pretty well for me, I will send you the jar & take a look again.

**Comment by EsGibtKeineMitte** [comment]
So I have tried to reproduce this bug, but it was not yet possible. Maybe it has something to do with your maven. If it would have been shaded, the error wouldn’t appear in de.leonhard.
Are you using the original jar file created from maven?
