### ISSUE TITLE
Does not save Double

### ISSUE THREAD

**Issue by justin393** [JavaFactoryDev/LightningStorage#8]
**Describe the bug**
When you do json.set("Path", value) and pass value as a double, it saves an int to the file instead of a double.

double x = loc.getX();
json.set("Sirens." + openId + ".X", x);

leads to a value in the .json file of ->   "X": -9992,
calling json.getDouble("Sirens." + i + ".X") then returns the int instead of a double

**Comment by JavaFactoryDev** [comment]
Thanks for your feedback. This issue will be resolved in 2.4:)

**Comment by JavaFactoryDev** [comment]
Fixed:)
